name: Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.changed_files, '*.go')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25

      - name: Run tests
        run: go test -v ./...
